### PR TITLE
List all by chunks

### PR DESCRIPTION
**Pull request by lud4ik**
Related https://github.com/tailhook/aio-s3/pull/1
Using:

``` python
for batch in bu.list_by_chunks("events", chunk_size=100):
    for key in (yield from batch):
        print(key)
```

### CODE REVIEW

**Comment by tailhook** [comment]
Sorry, but your solution seems to be too complicated for the task. I've done in more concise way: https://github.com/tailhook/aio-s3/commit/1b95e34f19fd79d9538a936675c4b0fb593dcce4

**Comment by lud4ik** [comment]
I didn't know that coroutine can be a generator. Why for is it needed at all if it works without it?

**Comment by tailhook** [comment]
> I didn't know that coroutine can be a generator. Why for is it needed at all if it works without it?

1. Coroutine is essentially a generator in the first place
2. The `@asyncio.coroutine` decorator is *mosty* for documentation purposes
3. The `@asyncio.coroutine` wraps functions that are not coroutines into one-iteration coroutines. Effectively ensuring that function is always coroutine
4. Also there is `PYTHONASYNCIODEBUG` which works only for decorated coroutines

**Comment by lud4ik** [comment]
1) I remember you said that you can't have yield and yield from in one function. 
What's the difference between generator with "yield" and "yield from"?

**Comment by tailhook** [comment]
Ah, sorry, the decorators were obviously wrong in this case.

**Pull request closed without merging**
