### PR TITLE
Add marker to list api

### PR DESCRIPTION
**Pull request by lud4ik**

### CODE REVIEW

**Comment by tailhook** [comment]
Well, I finally need this one myself. Just to make sure, @lud4ik, you don't work on it any more?

**Comment by lud4ik** [comment]
I didn't work at it at all. I just know s3 API and wanted to give an advice. I would say no if I had the ability to write python code more often. So if you don't reject, I can do it.

**Comment by lud4ik** [comment]
Works, but maybe need additional checks:
``` python
import asyncio
from aios3.bucket import Bucket


@asyncio.coroutine
def main():
    bu = Bucket('b',
                aws_region='eu-west-1',
                aws_endpoint='s3-eu-west-1.amazonaws.com',
                aws_key='x',
                aws_secret='x')

    for fut in bu.list_by_chunks("events"):
        batch = yield from fut
        print(len(batch))
        for key in batch:
            print(key)


asyncio.get_event_loop().run_until_complete(main())
```
https://github.com/lud4ik/aio-s3/commit/454dd84a28be903b3a4ddae8f78c7dee90e9d4a1

**Comment by tailhook** [comment]
> Works, but maybe need additional checks:
API looks Okay. I will look at implementation tomorrow.

> Interesting how your MultipartUpload works with methods that have yield from and are not coroutines. User have to create tasks with them?

This is obviously a (somewhat documentational) bug. Python doesn't raise any exceptions when generator is not wrapped by `asyncio.coroutine` decorator

> result.close() need only on POST and DELETE requests be called?

From quick skimming it looks like ok. You don't have to call close() when you've done read() on the request (but need close() when you do request.**content**.read()). And download method obviously can't close a request.

(BTW, please create separate issues for this kind of unrelated bugs)

**Comment by lud4ik** [comment]
> (BTW, please create separate issues for this kind of unrelated bugs)
I'm not sure if I've understood everything right, so you'll do it much better.

**Pull request closed without merging**
